#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "schedule.h"
#include "linkedList.h"

/* run this program using the console pauser or add your own getch, system("pause") or input loop */


int main(int argc, char *argv[]) {
	
	int exit_flag = 0;
	FILE *fp;
	
	char name[200];
	char place[100], typeName[100];	
	size_t size;
	int month;
	int day;
	int type;
	void *list;
	void *ndPtr;
	void *schedInfo;
	int option;
	int cnt;
	char buf[100];
	char *ptr;
	char *plcPtr;
	int i = 0;
	
	//1. FILE pointer open & error handling
	if ((fp = fopen("schedule.dat", "r")) == NULL)
	{
		printf("Can not find or open the file\n");
		return -1;
	}
	
	//initializing the list
	printf("Reading the data files... \n");
	list = (void*)list_genList();
	
	
	
	
	//2. read from the file
	while ((fgets(buf, sizeof(buf), fp)) != NULL)
	{	
		ptr = strtok(buf, " ");
		if (ptr != NULL)
		{
			for (int j = 0; j < 5; j++)
			{
				if (j == 0)
					strcpy(name, ptr);
				else if (j == 1)
					strcpy(place, ptr);
				else if (j == 2)
					type = atoi(ptr);
				else if (j == 3)
					month = atoi(ptr);
				else if (j == 4)
					day = atoi(ptr);
				ptr = strtok(NULL, " ");
			}
		}

		
		//fill code here -- generate genSchedInfo structure by genSchedInfo function
		schedInfo = sched_genSchedInfo(name, place, type, month, day);
		//put the scheduling info instance generated by genSchedInfo function
		list_addTail(schedInfo, list);

		
		
	}
	
	
	//fill code here ---- close the file pointer
	free(schedInfo);
	printf("Read done! %i schedules are read\n", list_len(list));
	
	
	//program starts
	while(exit_flag == 0) 
	{
		//3. menu printing
		//fill code here ---- 
		printf("1. print all the schedules\n");
		printf("2. search for schedules in the month\n");
		printf("3. search for schedules in the place\n");
		printf("4. search for specific type schedule\n");
		printf("5. exit\n");

		//4. get option from keyboard
		//fill code here ----
		printf(" select an option: ");
		scanf("%d", &option);
		
		i = 0;
		switch(option)
		{
			case 1: //print all the schedules
				printf("printing all the schedules in the scheduler.....\n\n\n");
				
				ndPtr = list;
				while (list_isEndNode(ndPtr) == 0)
				{
					//file code here -- print count and each scheduling info element
					ndPtr = list_getNextNd(ndPtr); //get the next node from the list
					schedInfo = list_getNdObj(ndPtr); //get the object (scheduling info)
		
					//fill code this part - end
					printf("----------------------------------------\n");
					sched_print(schedInfo);
					printf("----------------------------------------\n");
				}
				
				break;
				
			case 2:
				printf("which month ? : ");
				scanf("%i", &month);
				
				ndPtr = list;
				while (list_isEndNode(ndPtr) == 0)
				{
					//file code here -- print scheduling info elements matching to the month
					ndPtr = list_getNextNd(ndPtr); //get the next node from the list
					schedInfo = list_getNdObj(ndPtr); //get the object (scheduling info)
					
					//fill code this part - end
					if (sched_getMonth(schedInfo) == (float)month)
					{
						printf("----------------------------------------\n");
						sched_print(schedInfo);
						printf("----------------------------------------\n");
					}
				}
				
				break;
				
			case 3:
				printf("which place ? : ");
				scanf("%s", place);
				
				ndPtr = list;
				while (list_isEndNode(ndPtr) == 0)
				{
					//file code here -- print scheduling info elements matching to the place
					ndPtr = list_getNextNd(ndPtr); //get the next node from the list
					schedInfo = list_getNdObj(ndPtr); //get the object (scheduling info)
					
					//fill code this part - end
					plcPtr = sched_getPlace(schedInfo);
					if (strcmp(place, sched_getPlace(schedInfo)) == NULL)
					{
						printf("----------------------------------------\n");
						sched_print(schedInfo);
						printf("----------------------------------------\n");						
					}
				}
				
				break;
				
			case 4:
				printf("which type ?\n");
				sched_printTypes();
				printf("your choice : ");
				scanf("%s", typeName);
				
				if((cnt = sched_convertType(typeName)) != -1)
				{
					ndPtr = list;
					while (list_isEndNode(ndPtr) == 0)
					{
						//file code here -- print scheduling info elements matching to the place
						ndPtr = list_getNextNd(ndPtr); //get the next node from the list
						schedInfo = list_getNdObj(ndPtr); //get the object (scheduling info)
						
						//fill code this part - end
						if (sched_getType(schedInfo) == cnt)
						{
							printf("----------------------------------------\n");
							sched_print(schedInfo);
							printf("----------------------------------------\n");
						}

					}
				}
				else
				{
					printf("wrong type name!\n");
				}
				break;
				
			case 5:
				printf("Bye!\n\n");
				exit_flag = 1;
				break;
				
			default:
				printf("wrong command! input again\n");
				break;
		}
		
		
	}
	
	fclose(fp);
	return 0;
}
